# TODO: update obs dims / transformer dims once vsim 8-leg model is configured
env:
  onset_start: 0
  onset_end: 1000000
  flip_prob: 0.5

params:
  algo:
    name: a2c_continuous

  model:
    name: transformer_masked_a2c_logstd

  network:
    name: dynamic_leg_transformer
    separate: False
    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    transformer:
      d_model: 208
      n_heads: 8
      n_layers: 1
      ffn: 832
      torso_dim: 11
      hip_dim: 5
      ankle_dim: 11

  config:
    name: ant_dynamic_transformer_p1
    env_name: ant-codesign-env
    multi_gpu: False
    ppo: True
    mixed_precision: True
    normalize_input: True
    normalize_value: True
    value_bootstrap: True
    num_actors: 4096
    reward_shaper:
      scale_value: 0.01
    normalize_advantage: True
    gamma: 0.98
    tau: 0.95
    learning_rate: 7e-4
    lr_schedule: adaptive
    schedule_type: legacy
    kl_threshold: 0.015
    score_to_win: 10000
    max_epochs: 1000
    save_best_after: 200
    save_frequency: 50
    grad_norm: 1.0
    entropy_coef: 0.001
    truncate_grads: True
    e_clip: 0.2
    horizon_length: 16
    minibatch_size: 32768
    mini_epochs: 4
    critic_coef: 2
    clip_value: True
    seq_length: 4
    bounds_loss_coef: 0.0
